session_name: face rec
visdom_port: 8097
device: cuda
datasets:
    - name: images
      location: ../preprocessed_64/
      size: 64

    - name: imdb
      location: ../data/
      size: 64

tester:
    name: lfw
    root: ../lfw_funneled/
    pairs_file: ./lfw_test_pair.txt
    batch_size: 128
    similarity: cosine

trainer:
    batch_size: 256
    num_worker: 32
    max_epoch: 50
    save_interval: 2000
    test_interval: 500
    iter_n: 0
    display: True
    print_freq: 10
    num_workers: 32
    clip_grad: 15
    n_accumulations: 1

optimizer:
    name: SGD
    lr: 0.005
    weight_decay: 1.e-6
    momentum: 0.95

loss:
    name: cross_entropy
    balance: True

model:
    name: resnet_face50
    use_se: False

metric:
    name: ArcMarginProduct
    dim: 512
    s: 64

scheduler:
    name: NoSched
