session_name: face rec
visdom_port: 8097
device: cuda
datasets:
    - name: images
      location: ../preprocessed_64/
      size: 64

    - name: imdb
      location: ../data/
      size: 64

testers:
    - type: pairwise
      name: lfw
      root: ../lfw_funneled/
      pairs_file: ./lfw_test_pair.txt
      batch_size: 128
      similarity: cosine

trainer:
    batch_size: 340
    num_worker: 32
    max_epoch: 50
    save_interval: 2000
    test_interval: 200
    iter_n: 0
    display: True
    print_freq: 10
    num_workers: 32
    clip_grad: 100
    n_accumulations: 1
    ortho_reg: False

optimizer:
    name: SGD
    lr: 0.005
    weight_decay: 1.e-6
    momentum: 0.95
    nesterov: False

loss:
    name: cross_entropy
    balance: True

model:
    name: resnet34
    use_se: False

metric:
    name: FixedAdaCos

scheduler:
    name: CurriculumScheduler
    schedule:
        - [0, 0.02, 0.3]
        - [500, 0.02, 0.3]

        - [37000, 1, 0.9]
        - [56000, 1, 0.9]

        - [90000, 0.02, 0.95]
        - [100000, 0.02, 0.95]
        - [130000, 0.0001, 0.99]

