session_name: face rec
visdom_port: 8097
device: cuda
datasets:
    - name: images
      location: ../preprocessed_64/
      size: 64

    - name: imdb
      location: ../data/
      size: 64

tester:
    name: lfw
    root: ../lfw_funneled/
    pairs_file: ./lfw_test_pair.txt
    batch_size: 64
    similarity: cosine

trainer:
    batch_size: 128
    num_worker: 32
    max_epoch: 50
    save_interval: 2000
    test_interval: 1000
    iter_n: 0
    display: True
    print_freq: 10
    num_workers: 32
    clip_grad: 5

optimizer:
    name: SGD
    lr: 0.1
    momentum: 0.9
    weight_decay: 1.e-6
    #dampening: 0.1
    nesterov: True

loss:
    name: cross_entropy
    balance: True

model:
    name: resnet_face50
    use_se: False

metric:
    name: ArcMarginProduct
    dim: 512

scheduler:
    name: CurriculumScheduler
    schedule:
        - [0, 0.01, 0.9]
        - [40000, 5, 0.7]
        - [80000, 0.01, 0.9]
        - [100000, 0.0001, 0.98]
